apiVersion: v1
kind: Secret
metadata:
  name: cinder-csi-cloud-config
  namespace: kube-system
type: Opaque
stringData:
  cloud.conf: |
    [Global]
    auth-url = https://REPLACE_ME_KEYSTONE_HOST:5000/v3
    region = RegionOne
    interface = public
    identity-api-version = 3
    auth-type = v3applicationcredential
    application-credential-id = REPLACE_ME_APP_CRED_ID
    application-credential-secret = REPLACE_ME_APP_CRED_SECRET
    ca-file = /etc/config/pki/ca.crt
